sudo: enabled

dist: xenial

language: generic

branches:
  only:
    - master

git:
  submodules: false
  
env:
  global:
    - E3_PATH=${TRAVIS_BUILD_DIR}/epics
    - MOD_GA=eal
  matrix:
    - SESSION=1 BASE=3.15.5  TAG=3.15.5   REQUIRE=3.1.0  MOD_GB=4
    - SESSION=2 BASE=3.15.6  TAG=3.15.6   REQUIRE=3.1.0  MOD_GB=4
    - SESSION=3 BASE=7.0.2.1 TAG=7.0.2.1  REQUIRE=3.1.0  MOD_GB=o
    - SESSION=4 BASE=7.0.3   TAG=7.0.3    REQUIRE=3.1.0  MOD_GB=o
       
before_install:
  - sudo apt-get -qq update  > /dev/null 2>&1 
  - sudo apt-get install -y linux-headers-$(uname -r)   > /dev/null 2>&1 
  - sudo apt-get install -y build-essential realpath ipmitool libtool automake tclx  tree screen re2c darcs  > /dev/null 2>&1 
  - sudo apt-get install -y libreadline-dev libxt-dev x11proto-print-dev libxmu-headers libxmu-dev libxpm-dev libxmuu-dev libxmuu1 libpcre++-dev python-dev libnetcdf-dev libhdf5-dev libpng-dev libbz2-dev libxml2-dev libusb-dev libusb-1.0-0-dev libudev-dev libsnmp-dev libraw1394-dev libboost-dev libboost-regex-dev libboost-filesystem-dev libopencv-dev > /dev/null 2>&1
  - sudo apt-get install -y libtirpc-dev > /dev/null 2>&1
  - bash .ci/before_install_conf.bash > /dev/null 2>&1
  - bash e3_building_config.bash -y -t "${E3_PATH}" -b "${BASE}" -r "${REQUIRE}" -c "${TAG}" setup > /dev/null 2>&1

install:
  - bash e3.bash -${MOD_GA}${MOD_GB} call   > /dev/null 2>&1
  - bash e3.bash gbase                      > /dev/null 2>&1
  - bash e3.bash ibase                      > /dev/null 2>&1
  - bash e3.bash bbase                      
  - bash e3.bash req                        > /dev/null 2>&1
#  - bash e3.bash greq
#  - cd e3-require && git checkout devel/local && cd ..
#  - make -C e3-require init
#  - make -C e3-require build
#  - make -C e3-require install
  - bash e3.bash -ct mod                    > /dev/null 2>&1
  - bash e3.bash -ifelo mod                 > /dev/null 2>&1
  - bash e3.bash -ao${MOD_GB}  mod          > /dev/null 2>&1

after_success:
  - bash e3.bash -${MOD_GA}${MOD_GB} cmd
  - source ${E3_PATH}/base-${BASE}/require/${REQUIRE}/bin/setE3Env.bash
  - bash .ci/screen.bash ${SESSION} .cmd


  
 
